# Generated by Django 4.1.6 on 2023-06-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.AutoField(db_column='idMantencion', primary_key=True, serialize=False)),
                ('mantencion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='rut',
            field=models.CharField(db_column='rut', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('modelo', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=20)),
                ('diagnostico', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
                ('id_mantencion', models.ForeignKey(db_column='idMantencion', on_delete=django.db.models.deletion.CASCADE, to='clientes.mantencion')),
                ('mecanico', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='clientes.mecanico')),
            ],
        ),
    ]
