# Generated by Django 4.1.6 on 2023-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_atencion_id_atencion_id_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='patente',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
