# Generated by Django 4.1.6 on 2023-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_atencion_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='patente',
            field=models.CharField(max_length=20),
        ),
    ]
